### PR TITLE
Fix version switches, remove --stable flag

### LINKED ISSUE #151: --latest & --stable have no effect
When doing `./start_ocean.sh --latest` I expect to get the latest published versions of all components. At the moment it gets those component versions which are not the latest published versions:

- brizo:v0.3.1 (should be v0.3.8)
- aquarius:v0.2.2 (should be v0.2.5)
- keeper-contracts:v0.9.0 (should be v0.9.7)

### LINKED ISSUE #157: Remove --stable flag
Not sure what exactly the stable switch is supposed to mean, stable can only be defined by a certain combination of component versions, not by a branch of one component. Hence, our default versions, manually set at top of `start_ocean.sh` script should be what's considered stable. Just grabbing the `master` branch of any component does in no way guarantee what users see in the end is stable. For whatever reason we have introduced 3 different sets of version combinations: default, "stable" & "latest" and it's not clear to outside users what the difference between default and stable is. 

At the moment, none of those 3 options will bring up something working from end to end, so nothing really is "stable".

Best way would be to remove the confusing stable switch, and change our nomenclatura to:
- default: `./start_ocean.sh`, referring to a manually set combination of releases
- latest: `./start_ocean.sh --latest`, should refer to latest release versions of each component

With that, referring to release versions instead of branches, we could do away with the `master/develop` split-up too, which adds a lot of friction for more agile release processes. So `master` would be always the dev version, and a release is what's considered stable for that component.

### PR DESCRIPTION
**Pull request by kremalicious**
Specifically set latest & stable versions, no need to check for env variables existence in version switches.

- Closes #151 
- Closes #157

### CODE REVIEW

File: start_ocean.sh [hunk 1]
```diff
@@ -138,17 +138,17 @@ while :; do
         # Version switches
         #################################################
         --latest)
-            export AQUARIUS_VERSION=${AQUARIUS_VERSION:-latest}
-            export BRIZO_VERSION=${BRIZO_VERSION:-latest}
-            export KEEPER_VERSION=${KEEPER_VERSION:-latest}
-            export PLEUSTON_VERSION=${PLEUSTON_VERSION:-latest}
+            export AQUARIUS_VERSION="latest"
```
Comment (ttmc) [inline start_ocean.sh]: This changes the meaning of the `--latest` option (and the `--stable` option, below). The bash script code is easier to read, for sure, but the README.md file must also be updated to explain what those options actually do now.
